import os

configfile: "config.yaml"

name = config["name"]
count = config["count"]

rule all:
    input:
        expand("output/hello_{i}.txt", i=range(count))

rule hello:
    output:
        "output/hello_{i}.txt"
    conda:
        "envs/hello.yaml"
    threads: 1
    resources:
        mem_mb=100  # simple estimate
    shell:
        """
        echo "hello {name}{wildcards.i}" > {output}
        """
